### PR TITLE
Fix-#100

### PR DESCRIPTION
**Pull request by Dragonfly911117**
### Fixes
- #100 

#### API Changes
- `/api/account`: Now includes `shop_uuid`, `shop_name`, and `shop_is_active`, but note that the value is **always** `NULL`, even if there's an existing shop under the account.
- `/api/account/all`: Similar to `/api/account`, now returns `shop_uuid`, `shop_name`, and `shop_is_active` but with values.

#### Misc Changes
- The Account model has been updated to include `shop_uuid`, `shop_name`, and `shop_is_active` as attributes.

### CODE REVIEW

**Review by Vghxv — APPROVED** [review]

**Comment by garry911128** [comment]
why shop_is_active is always NULL in /api/account
你可以直接不給欄位?

**Comment by Dragonfly911117** [comment]
> why shop_is_active is always NULL in /api/account 你可以直接不給欄位?

可以，但我不想多寫一個 model 針對這個 API

**Comment by Dragonfly911117** [comment]
看大哥 @Vghxv

**Comment by Vghxv** [comment]
我覺得多一個model 可以讓前端拿到的資料更乾淨
但看你要不要加

**Pull request merged**
